language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.1
otp_release:
  - 20.3
  - 21.2
env:
  - PLT_DIR=$HOME/.plt
before_script:
  - mkdir -p $PLT_DIR
  - mix deps.compile
  - MIX_ENV=test mix deps.compile
  - travis_wait mix dialyzer --plt
script:
  - mix compile --force --verbose --warnings-as-errors
  - mix test --trace
  - mix dialyzer --no-compile --no-check --halt-exit-status
  - mix credo
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.8.1" ]]; then mix format --check-formatted; fi
cache:
  directories:
    - $PLT_DIR
